# Generated by Django 4.0.2 on 2022-06-01 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boglanish',
            name='fullname_en',
        ),
        migrations.RemoveField(
            model_name='boglanish',
            name='fullname_ru',
        ),
        migrations.RemoveField(
            model_name='boglanish',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='boglanish',
            name='text_ru',
        ),
    ]
