# Generated by Django 4.0.2 on 2022-06-02 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_boglanish_fullname_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='fullname_en',
        ),
        migrations.RemoveField(
            model_name='application',
            name='fullname_ru',
        ),
        migrations.RemoveField(
            model_name='application',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='application',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='fullname_en',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='fullname_ru',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='text_ru',
        ),
    ]
